name: Build Flutter Stable

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build \
            -t chiragji/flutter-aio:latest \
            --push \
            --platform linux/amd64 \
            .